"""Beat specification for claude-liam-walker-tank-gamedev (godot-gamedev, walker mode).
Narration spells the tank's name phonetically ("Yoon-chee Zee") for Kokoro; on screen it is YunqiZ.
Code beats name a (path, first_line, last_line) range; make_sheet.py reads the text verbatim.
cue_spec entries bind a highlight to the first narrated word of `phrase` (bind_cues.py).
"""

TITLE = "Walker-TANK: Tracing One Tank Hull"
SLUG = "claude-liam-walker-tank-gamedev"
PROJECT = "walker-TANK"
SRC = "Source: walker-TANK commit 4616fc7"

METADATA = {
    "title": TITLE, "slug": SLUG, "topic": "GODOT · WALKER · GAMEDEV", "kind": "gamedev", "mode": "walker",
    "brand": "claude-liam", "audience": "CSYE7270 students and makers building small games with Walker + Claude Code",
    "register": "Teardown", "engine": "kokoro", "voice": "am_onyx", "voice_kokoro": "am_onyx",
    "palette": "claude", "style_preset": "claude", "ground": "#FAF9F5", "aspect_ratio": "16:9", "fit": "contain",
    "captions": False, "channel": "@NikBearBrown", "channel_title": "@NikBearBrown", "folderLabel": "@NikBearBrown",
    "greeting": "Ciao, Liam", "greeting_note": "hello lexicon: Ciao (Italian). Liam never takes Wagwan.",
    "persona": "Liam (in for Bear)", "presenter": "Liam (in for Bear)", "in_for_bear": True, "fps": 30,
    "teaching_contract": "code-then-result-v1",
    "game": {"name": "walker-TANK", "path": "../..", "revision": "4616fc762d5b1b64c770cdc21d1662684cb13d46",
             "engine": "Godot 4.7.2.stable.official.ed1daf0bf"},
    "note": "godot-gamedev walker mode. Gameplay beats are pre-trimmed native 4K Movie Maker captures (scripted input, logged), "
            "mixed with the game's own recorded audio. No paid API, no upload, no game change.",
}


def code(bid, title, path, a, z, narration, notes, cues, size=30, act="CODE"):
    return {"beat_id": bid, "act": act, "role_note": f"Code beat: {path} lines {a}-{z}, verbatim.",
            "narration_text": narration, "pattern": "GodotDevWorkbench", "code_src": (path, a, z),
            "shot": {"type": "GRAPHIC", "class": "SHOW", "source": "remotion",
                     "show": [{"at": "0.0", "event": "Godot editor reconstruction: verbatim excerpt with line numbers"}] +
                             [{"at": c["phrase"], "event": f"line {c['line']} highlighted: {c['label']}"} for c in cues]},
            "props": {"mode": "code", "title": title, "project": PROJECT, "source": SRC + f" · {path} lines {a}–{z}",
                      "codeFontSize": size, "inspectorLabel": "Source notes — not Inspector values",
                      "notes": [{"label": k, "value": v} for k, v in notes], "cues": [], "output": []},
            "cue_spec": [{"phrase": c["phrase"], "line": c["line"], "label": c["label"]} for c in cues]}


def figure(bid, title, status, image, narration, cards, cues, excerpt="", act="ASSET", dense=False, label=""):
    return {"beat_id": bid, "act": act, "role_note": f"Figure beat: {image}",
            "narration_text": narration, "pattern": "GodotDesignFigure", "image_src": image,
            "shot": {"type": "GRAPHIC", "class": "SHOW", "source": "remotion",
                     "show": [{"at": "0.0", "event": f"real evidence image: {image}"}] +
                             [{"at": c[0], "event": f"card {c[1]} lit: {cards[c[1]][0]}"} for c in cues]},
            "props": {"title": title, "status": status, "imageLabel": label, "excerpt": excerpt, "source": SRC,
                      "cards": [{"label": l, "text": t} for l, t in cards], "cues": [], "dense": dense},
            "cue_spec": [{"phrase": p, "card": i} for p, i in cues]}


def gameplay(bid, act, narration, role):
    return {"beat_id": bid, "act": act, "kind": "gameplay", "role_note": role, "narration_text": narration,
            "shot": {"type": "VIDEO", "class": "SHOW", "source": "own", "treatment": "none", "media": f"media/{bid}.mp4",
                     "evidence_media": f"media/{bid}.mp4", "capture": {"id": "run-01", "method": "scripted-input",
                                 "clip_policy": "pre-trimmed to the exact render duration; never retimed"}}}


PENDING = "[PLACEHOLDER] narration written after the capture is inspected"

BEATS = [
    {"beat_id": "B00", "act": "ASK", "role_note": "COLD OPEN + walker B00. Illustrative reconstruction of the GDD prompt.",
     "narration_text": "Ciao, this is Liam, in for Bear. Today we're taking apart walker-TANK, a Godot asset slice for CSYE seventy-two seventy, Assignment Two. The prompt on screen is an illustrative reconstruction, not the original chat. The question for this film: how did one generated tank get from a design sheet into the running game, and what do we actually know works?",
     "pattern": "ClaudeComposerAsk",
     "shot": {"type": "GRAPHIC", "class": "SHOW", "source": "remotion",
              "show": [{"at": "0.02", "event": "composer on cream; greeting 'Ciao, Liam'"},
                       {"at": "0.15", "event": "the Walker prompt types in, describing this game's actual idea"},
                       {"at": "0.60", "event": "send arms terracotta"},
                       {"at": "0.72", "event": "result lines land; the first labels the prompt a reconstruction"}]},
     "props": {"greeting": "Ciao, Liam", "topic": "GODOT · WALKER", "segment": "walker-TANK",
               "command": "Please use Walker to convert my game design document about walker-TANK — a top-down tank battle where my tank, YunqiZ, hides behind brick cover that breaks under fire and destroys three enemy tanks — into a small playable Godot asset slice that uses my generated art, sound effects and music.",
               "runningText": "reading the game design document…", "folderLabel": "@NikBearBrown", "modelLabel": "Claude",
               "effortLabel": "High", "animateTyping": True, "largeText": True,
               "output": ["Illustrative reconstruction, not a transcript.",
                          "Result: one arena, three enemy tanks, breakable cover.",
                          "Godot 4.7.2 · commit 4616fc7 · scripted-input captures."]}},
    {"beat_id": "B01", "act": "BLUF", "role_note": "walker B01: what was built. Misconception corrected: the model finished the tank -> started it.",
     "narration_text": "Walker-TANK is one arena: three enemy tanks, and brick cover that breaks. The tank, Yoon-chee Zee, came out of SDXL. But the model only started the tank. Guide images, cleanup scripts and the student's own choices finished it. That's the trail we'll follow.",
     "lead_silence_s": 0.8, "pattern": "BrutalistHesitantWriter",
     "qc": {"sparse_by_design": True, "sparse_reason": "BrutalistHesitantWriter types the overview line by line; mid-beat frames are partly empty cream by design."},
     "shot": {"type": "GRAPHIC", "class": "SHOW", "source": "remotion",
              "show": [{"at": "0.0", "event": "cream page; typing starts inside the 0.8 s lead silence"},
                       {"at": "0.5", "event": "'The model finished the tank.' types, pauses"},
                       {"at": "0.7", "event": "'finished' struck in terracotta, 'started' typed in"}]},
     "props": {"contextTitle": "What was built",
               "text": "walker-TANK: three enemy tanks,\ncover that breaks.\nYunqiZ came out of SDXL.\nThe model finished the tank.",
               "triggerWords": "finished", "replacementWords": "started", "fontSize": 68, "lineSpacing": 2.6,
               "align": "center", "seed": "7270-tank", "mistakeRate": 2, "hesitateWithin": 0, "hesitateBetween": 1,
               "charMs": 8, "ink": "#3D3929", "accent": "#D97757", "bg": "#FAF9F5"}},
    figure("B02", "The Assignment and the Setup", "ASSIGNMENT 2 BRIEF · verbatim", "evidence/ev-assignment.png",
           "The assignment: design the look and sound first, generate the art, sound and music, and prove them in a small playable Godot scene. The minimum is on screen: the character in two states plus one environment asset, four sound events, and one music loop with no click. This slice started from an empty Godot project. Everything you'll see is commit four six one six F C seven, on Godot four point seven point two.",
           [("Started from", "an empty Godot 4 project"), ("Engine", "Godot 4.7.2 stable"),
            ("Source shown", "commit 4616fc7"), ("Captures", "scripted input, 4K")],
           [("empty", 0), ("commit", 2)], act="SETUP"),
    gameplay("B03", "CONCEPT", "This is the running slice, rendered natively in 4K by Godot's Movie Maker. A script presses the real keys and moves the real cursor, so this is not a human playtest. The concept: one tank, three enemies, and cover that breaks. Hide, pick your moment, and fire.", "Concept: the opening of the real take (idle at spawn, music)."),
    {"beat_id": "B04", "act": "CONCEPT", "kind": "gameplay", "role_note": "Pillars: 2x2 grid of four real clips from run-01, labeled with the CONCEPT.md pillar names verbatim.",
     "narration_text": 'The four pillars from the concept. Cold steel battlefield: grey-brown ground and a slow drum loop. Cover is not permanent: walls crack, then break. Every shot has weight: recoil, a flash, a deep cannon. And damage is information: smoke, then fire.', "shot": {"type": "VIDEO", "class": "SHOW", "source": "own", "treatment": "none", "media": "media/B04.mp4",
                                         "capture": {"id": "run-01", "method": "scripted-input", "clip_policy": "four real intervals, each unretimed, tiled 2x2 at half size"}}},
    figure("B05", "Character Sheet: The Silhouette Test", "PLANNING SKETCH · code-drawn by Claude · not model output",
           "evidence/ev-silhouette.png",
           "Here's where the hull starts: the character sheet. Yoon-chee Zee is filled solid black at game size, about sixty-four pixels across. The first box model failed: facing up and facing down looked the same. So the student added a wide dozer blade at the front and a narrower storage box at the back. Now the silhouette tells you which way the tank faces, before any texture exists.",
           [("Planned size", "about 64 px across"), ("First result", "up = down"),
            ("Front marker", "dozer blade, wider"), ("Rear marker", "storage box, narrower")],
           [("sixty-four", 0), ("failed", 1), ("dozer", 2), ("storage", 3)],
           excerpt="“with a plain box hull, the up and down facings were almost identical at 64 px” — CHARACTER-SHEET.md"),
    figure("B06", "First Try: The v1 Guide", "REJECTED · SDXL img2img on the v1 guide · student's thumbnails",
           "evidence/ev-v1-rejects.png",
           "The generation was image to image: Stable Diffusion XL starts from a guide picture. The first guide was flat boxes with black outlines. At denoise point five five, the output was the guide again. At point seven, still flat. At point eight, panel lines finally appear, and the dozer blade is gone. The student kept the seed and prompt fixed and changed one number, so the three are comparable.",
           [("0.55", "flat colour blocks"), ("0.70", "still flat"), ("0.80", "blade lost"), ("Held fixed", "seed + prompt")],
           [("denoise", 0), ("still flat", 1), ("panel lines", 2), ("fixed", 3)]),
    code("B07", "The Fix Was the Guide, Not the Denoise", "design/guides/v2/draw_guides_v2.py", 14, 20,
         "The diagnosis: flat colors with outlines read as a flat drawing, so the model drew a flat drawing. Claude rewrote the guide in code. This function gives every face its own gradient, a little lighter at the top and a little darker at the bottom. A second script adds grain and grime, with a fixed seed. Same tank, now shaded like an object.",
         [("Written by", "Claude, code-drawn, not a model"), ("Also v2", "texture_guides_v2.py: grain, seed 7"), ("Removed", "v1's black outlines")],
         [{"phrase": "lighter", "line": 18, "label": "each face: 1.12x lighter at the top, 0.82x at the bottom"},
          {"phrase": "grain", "line": 19, "label": "written out as an SVG linearGradient per face"}], size=28),
    figure("B08", "Result: v1 Guide Beside v2", "CODE-DRAWN GUIDES · design/guides and design/guides/v2",
           "evidence/ev-v1-v2-guides.png",
           "And that's the visible result of those lines. On the left, v1: flat fills and hard outlines. On the right, v2: the faces shade from light to dark, and there are road wheels, deck panels and blade ribs for the model to follow. It's the same box model underneath, so the proportions from the character sheet survive.",
           [("v1", "flat fills, outlines"), ("v2", "shaded faces + detail"), ("Underneath", "same box model")],
           [("left", 0), ("right", 1), ("same box", 2)]),
    figure("B09", "Raw SDXL Output, Before Any Edit", "RAW MODEL OUTPUT · assets/raw/hull · not in-engine",
           "evidence/ev-raw-output.png",
           "Same seed, same prompt, the v2 guide, denoise point five five. This is the raw output, straight from the model, and these settings are read from the file's own metadata, not from the log. They match the asset log. Worn olive paint, rust, wheels, and the blade survived. At point six five, the model added a turret dome on the hull, so that one was rejected.",
           [("Read from", "the PNG's metadata"), ("Matches", "ASSET-LOG G-06"), ("Kept", "blade, box, facing"), ("0.65 rejected", "added a turret")],
           [("metadata", 0), ("match", 1), ("survived", 2), ("dome", 3)]),
    code("B10", "Cutout: Keep Every Large Part", "tools/cutout_hull.py", 18, 23,
         "Next, the white background has to go. The first cutout kept only the largest connected piece, and on the right-facing hull the dozer blade is a separate piece, so the blade vanished. The fix is these lines: keep every part bigger than two thousand pixels. One small catch for the student: the docstring at the top still describes the old rule.",
         [("Written by", "Claude (tools/)"), ("Bug caught", "v1 kept only the largest piece"), ("Stale", "line 3 docstring: old rule")],
         [{"phrase": "fix", "line": 18, "label": "the blade can be a separate piece"},
          {"phrase": "two thousand", "line": 22, "label": "keep every part of 2,000 px or more"},
          {"phrase": "catch", "line": 23, "label": "the docstring (line 3) was not updated"}], size=32),
    figure("B11", "Result: The Hull Check Sheet", "STUDENT'S CHECK SHEET · design/asset-log/check_hull_v2.png",
           "evidence/ev-check-hull-v2.png",
           "Here's the check sheet that caught it. Top row: the cutouts, and the right-facing blade is back. Second row: the red outline of the v2 guide over each hull; the log reports an overlap of point nine nine. Then the turret guide on top, and finally sixty-four pixels on mud, with the silhouette beside it. The facing still reads.",
           [("Row 1", "cutout, blade kept"), ("Row 2", "guide outline"), ("Row 3", "turret guide"), ("Row 4", "64 px on mud")],
           [("Top row", 0), ("Second", 1), ("turret guide", 2), ("sixty-four", 3)]),
    code("B12", "Colour Match to the Sheet", "tools/process_sprites.py", 30, 37,
         "Then colour. The down hull came out about fifteen to twenty percent brighter than the right one. This function measures each sprite's average olive, computes one gain per colour channel toward the sheet's main paint colour, and applies it only where a pixel is olive. Steel, tracks and barrel keep their own colour.",
         [("Target", "#4B5320, line 12"), ("Weight", "olive pixels only, line 25"), ("Clamp", "gain 0.75–1.3 per channel")],
         [{"phrase": "measures", "line": 32, "label": "the sprite's mean olive, before"},
          {"phrase": "gain", "line": 33, "label": "one gain per channel toward #4B5320"},
          {"phrase": "only where", "line": 35, "label": "blended in only on olive pixels"}], size=31),
    figure("B13", "Result: All Eight Facings", "STUDENT'S CHECK SHEET · design/asset-log/check_final_8dir.png",
           "evidence/ev-final-8dir.png",
           "The result: hull and turret in all eight facings. Five were generated; down-left, left and up-left are mirrors. The olive now matches across directions, and the white stripe, painted on by a script, reads in every one. The log is honest about the leftovers: the up and right turrets have no commander cupola, a one-to-two pixel difference at game size.",
           [("Facings", "5 generated + 3 mirrored"), ("Olive", "matched to #4B5320"), ("Stripe", "painted by script"), ("Known issue", "no cupola: up, right")],
           [("Five", 0), ("olive", 1), ("stripe", 2), ("cupola", 3)]),
    code("B14", "Hull Follows the Keys, Turret Follows the Mouse", "scripts/tank.gd", 123, 131,
         "Now into the engine. In tank dot G D, the hull picks one of the eight sprites from the movement direction, and only while you're moving. The turret picks its own from the aim. Line one twenty-eight is the state change: moving gives a fast track rumble, idle gives a slower engine shake a third the size. Those are code, not generated frames.",
         [("Facing", "_slot_for(), lines 92–95"), ("Mirrors", "SLOT_FLIP, line 16"), ("Written by", "Claude (all GDScript)")],
         [{"phrase": "hull picks", "line": 124, "label": "hull: the movement direction, only while moving"},
          {"phrase": "turret picks", "line": 125, "label": "turret: the aim direction"},
          {"phrase": "state change", "line": 128, "label": "moving 0.6 px at 30 rad/s; idle 0.2 px at 12 rad/s"}], size=27),
    gameplay("B15", "STATES", "Five seconds idle: the hull rests and shivers, while the turret follows the cursor. Then eight short drives, one per facing. The enemies aren't waiting: two hits land, and the smoke starts.", "Result of B14: idle at spawn, then the eight-leg drive (real take)."),
    code("B16", "Cover That Breaks", "scripts/cover.gd", 33, 45,
         "Cover dot G D. Every accepted hit counts, and each one plays a single cover sound. At two hits the wall swaps to its cracked texture. At four it's broken, and its collision shape is switched off, so it stops blocking shells and tanks.",
         [("Crack", "HITS_TO_CRACK = 2, line 5"), ("Break", "HITS_TO_BREAK = 4, line 6"), ("Broken", "no longer blocks shells")],
         [{"phrase": "hits", "line": 36, "label": "every accepted hit counts"},
          {"phrase": "sound", "line": 39, "label": "one cover-hit sound per hit"},
          {"phrase": "broken", "line": 45, "label": "broken: the collision shape turns off"}], size=23),
    gameplay("B17", "STATES", 'Watch the left wall: cracked at two hits, broken at four.', "Result of B16: fire into the nearest cover until it breaks (real take)."),
    code("B18", "Damage Is Information", "scripts/tank.gd", 195, 198,
         "Damage is information. After every hit that isn't fatal, this function compares health with the maximum. At sixty percent or less, the smoke turns on. At thirty or less, the flames too. A fatal hit skips the hit sound and plays the explosion instead.",
         [("Hit window", "0.3 s invulnerable, line 166"), ("Hit sound", "non-fatal hits only, line 173"), ("Effects", "CPUParticles2D, code")],
         [{"phrase": "sixty", "line": 197, "label": "smoke at 60% health or less"},
          {"phrase": "thirty", "line": 198, "label": "flames at 30% or less"}], size=40),
    gameplay("B19", "STATES", 'Second life, already hit once. The next hit drops it to half health: smoke. It takes out a second enemy, and the camera shakes. One more hit, a quarter health: flames, and the bar turns red. Each hit gets its own metallic clang.', "Result of B18: hits, smoke, flames (real take)."),
    code("B20", "Destroyed, Then Back", "scripts/main.gd", 257, 268,
         "When Yoon-chee Zee dies, main dot G D stops the music first, so only the explosion's tail is left. It shows the respawn message, waits two seconds, puts the tank back at the spawn with full health, and restarts the music from the top.",
         [("Runs once", "is_dead set first, tank.gd 182"), ("Respawn", "2.0 s, full health, at SPAWN"), ("Wrecks", "destroyed enemies stay")],
         [{"phrase": "music", "line": 258, "label": "failure: the music stops"},
          {"phrase": "two seconds", "line": 262, "label": "wait 2.0 s"},
          {"phrase": "restarts", "line": 267, "label": "respawn: the music restarts from the top"}], size=23),
    gameplay("B21", "STATES", 'First death: the music cuts, and only the explosion rings out. Two seconds later, back at spawn, and the music restarts. An enemy goes down, then Escape pauses everything, and the music holds its place.', "Result of B20: YunqiZ destroyed, music cut, respawn, music restarts (real take)."),
    code("B22", "The Last Enemy", "scripts/main.gd", 271, 280,
         'The last enemy. The counter drops, and when it reaches zero, only once, level won is set, the controls switch off, the music stops, and a single victory sound plays. Setting the flag before the sound is what keeps it from firing twice.',
         [("Guard", "level_won set before the sound"), ("Controls", "player input switched off"), ("Screen", "_show_victory(): 3 / 3")],
         [{"phrase": "zero", "line": 275, "label": "remaining reaches zero, once"},
          {"phrase": "music", "line": 278, "label": "music stops"},
          {"phrase": "victory", "line": 279, "label": "one victory sound"}], size=29),
    gameplay("B23", "STATES", 'Second death, and respawn. Now, just the game.', "Result of B22 (narrated lead-in to the last kill)."),
    {"beat_id": "B24", "act": "GAME AUDIO", "kind": "gameplay", "role_note": "Clearly labeled segment: the slice's own audio only, no narration.",
     "narration_text": "", "audio_policy": "game_only",
     "shot": {"type": "VIDEO", "class": "SHOW", "source": "own", "treatment": "none", "media": "media/B24.mp4",
              "capture": {"id": "run-01", "method": "scripted-input", "clip_policy": "pre-trimmed; never retimed; game audio only"}}},
    code("B25", "One Code Change: The Health Bar", "scripts/main.gd", 373, 379,
         "One code change, and its effect. In the student's playtest screenshots, the default grey health bar disappeared into the dark ground. Line two ninety-nine records that. The fix is line three seventy-eight: above sixty percent health the bar fills green, above thirty yellow, below that red. The same thresholds as the smoke and the fire.",
         [("Why, line 299", "grey fill hard to read on ground"), ("Fill", "StyleBoxFlat, lines 300–301"), ("Same as", "smoke 0.6, fire 0.3")],
         [{"phrase": "fix", "line": 378, "label": "green above 0.6, yellow above 0.3, else red"},
          {"phrase": "same thresholds", "line": 377, "label": "r = health / max_health"}], size=26),
    figure("B26", "Result: Before and After", "BEFORE: student's screenshot · AFTER: frames from run-01",
           "evidence/ev-healthbar.png", "Before, from the student's own screenshot: a grey bar you can barely see. After, three frames from this take: green at full health, yellow at half, red at a quarter. Same game state, now readable at a glance.",
           [("Before", "default grey fill"), ("After", "green / yellow / red"), ("Source", "main.gd line 378")],
           [("Before", 0), ("After", 1)]),
    code("B27", "The Automated Check", "tests/test_sound_triggers.gd", 39, 49,
         "Testing. The automated check loads the real game scene and counts how many times each event asks for a sound. Here, one shell touches the same cover twice. Notice it calls the shell's hit function by hand, twice, instead of waiting for physics. Expected: one hit, and one cover sound.",
         [("Runs", "the real main scene, headless"), ("Counts", "audio.gd play requests"), ("Shortcut", "calls _on_body_entered()")],
         [{"phrase": "one shell", "line": 43, "label": "a real shell node"},
          {"phrase": "by hand", "line": 47, "label": "the same contact, called twice"},
          {"phrase": "Expected", "line": 49, "label": "expect 1 cover-hit sound and 1 hit"}], size=26, act="TEST"),
    figure("B28", "Result: The Recorded Test Run", "RECORDED OUTPUT · run by Claude on an isolated copy, 2026-10-06",
           "evidence/ev-test-output.png",
           "I ran it on an isolated copy of this commit. Eight of eight pass, exit code zero. But look at the last lines. The test report says the leak warnings were fixed by freeing the scene. They still print: twenty-two leaked objects, and seven resources still in use. That doesn't fail the test, but the report's claim doesn't match this run.",
           [("Result", "8 / 8 PASS"), ("Exit code", "0"), ("Still printed", "leak warnings")],
           [("Eight", 0), ("zero", 1), ("still print", 2)], act="TEST"),
    figure("B29", "What the Test Can't Prove", "STUDENT'S PLAYTEST SCREENSHOT · design/test/play-05-muted.png",
           "evidence/ev-muted.png",
           "What that test can't prove: it counts requests to play a sound, not sound reaching your ears, and it skips physics timing by calling handlers directly. The rest was checked by a person. The student played with sound on, then muted, like this screenshot, and listened for the loop seam. Nobody else has played it yet, and the low cannon and explosion were never checked on laptop speakers.",
           [("Counts", "requests, not sound"), ("Skips", "physics timing"), ("By hand", "sound on + muted"), ("Not tested", "other players, laptops")],
           [("requests", 0), ("skips", 1), ("person", 2), ("Nobody", 3)], act="TEST"),
    figure("B30", "Which Model Made Which Asset", "FROM ASSET-LOG.md AND SOURCES.md · the real files",
           "evidence/ev-models.png",
           "Which model made which asset. Stable Diffusion XL Base one point oh, running locally in ComfyUI, made the hull and turret sprites, the three cover stages, and the ground. Stable Audio three Small, the S F X version, made the cannon, the cover hit, the tank hit and the explosion. The music version made the victory sting and the battle loop. The flashes, smoke, fire and explosions you saw are code particles, not model output.",
           [("SDXL Base 1.0", "sprites, cover, ground"), ("SA3 Small-SFX", "4 event sounds"), ("SA3 Small-Music", "victory + loop"), ("Code", "all particle effects")],
           [("Stable Diffusion", 0), ("S F X", 1), ("music version", 2), ("code particles", 3)], act="CREDITS"),
    figure("B31", "Who Decided What", "FROM FRICTIONAL.md, 2026-10-02 · turret denoise decision",
           "evidence/ev-turret-decision.png",
           "Who did what. The student chose the game, the pillars, the blade and the box, ran every generation, and judged every output. Claude drew the guides in code, drafted the prompts, and wrote the cleanup scripts and all the game code. The models made pixels and waveforms. One example from the log: the student first preferred denoise point seven five. Claude pointed out that the stripe was gone and the shape had drifted. The student chose point six.",
           [("Student", "chose, ran, judged"), ("Claude", "guides, prompts, code"), ("Models", "pixels + waveforms"), ("Final call", "student: 0.60")],
           [("student chose", 0), ("Claude drew", 1), ("models", 2), ("point six", 3)], act="CREDITS"),
    figure("B32", "Still Uncertain, and the Next Step", "LOGS vs FILES at commit 4616fc7",
           "evidence/ev-gaps.png",
           "What's still uncertain. The logs disagree about the kept down turret: the asset log says denoise point six, with an unrecorded seed. The file itself says point five five and gives the seed, which matches the Frictional log. The environment generations have no asset log rows, a few referenced check images aren't in this commit, and the fresh-copy run is still marked to do. Next step toward the full game: give the enemy tanks their own generated design, instead of a grey tint.",
           [("Disagree", "turret T-12 settings"), ("Missing", "env rows, check images"), ("To do", "fresh-copy run"), ("Next step", "real enemy tank design")],
           [("disagree", 0), ("environment", 1), ("fresh-copy", 2), ("Next step", 3)], act="UNCERTAIN"),
    {"beat_id": "B33", "act": "VERDICT", "role_note": "Verdict separates observed, recorded, not shown, untested, and log fixes.",
     "narration_text": 'Verdict. Observed in a scripted run, not a human playtest: all eight facings, idle and moving, firing, cover cracking and breaking, smoke, flames, destruction, respawn, pause and victory, with all five sound events. The music cut on each death, restarted on respawn, held its place on pause, and stopped at victory. The test passes eight of eight, with leak warnings the report says are gone. Not shown: the mute keys and restart. Untested: other players and laptop speakers. And the logs need a pass.', "pattern": "ClaudeVerdictArtifact",
     "shot": {"type": "GRAPHIC", "class": "SHOW", "source": "remotion",
              "show": [{"at": "0.05", "event": "verdict artifact page"}, {"at": "0.2", "event": "observed lines"},
                       {"at": "0.6", "event": "recorded / not shown / untested / to fix"}]},
     "props": {"artifactTitle": "Verdict", "artifactHeading": "walker-TANK, commit 4616fc7.", "brandLabel": "@NikBearBrown",
               "artifactLines": [
                   "Observed (scripted run): 8 facings, idle, moving, firing, cover crack + break.",
                   "Observed: smoke, flames, destroyed, respawn, pause, victory; all 5 sound events.",
                   "Music: cut on death, restarts on respawn, holds on pause, stops at victory.",
                   "Recorded: test 8/8, exit 0; leak warnings still print. Untested: other players.",
                   "To fix: turret row T-12, environment log rows, missing check images."]}},
    {"beat_id": "B34", "act": "HANDOFF", "role_note": "HANDOFF: the prompt is read aloud verbatim and discussed; Liam signs off here.",
     "narration_text": "Your turn. Here's the prompt. Please use Walker to add one new sound event to my walker-TANK slice: a short click when the zero point eight second reload finishes. First add it to my event-to-sound map, and predict how many clicks ten seconds of held fire should give. Then extend tests slash test sound triggers to count it, and only then edit the game code. That prompt puts the prediction and the test before the code, the same order this slice used for its other five sounds. When the answer comes back, compare its number with yours before you listen. Then play it, sound on and muted. Liam, in for Bear.",
     "pattern": "ClaudeComposerAsk",
     "shot": {"type": "GRAPHIC", "class": "SHOW", "source": "remotion",
              "show": [{"at": "0.02", "event": "composer; greeting 'Your turn.'"},
                       {"at": "0.08", "event": "the suggested Walker prompt types in while Liam reads it"},
                       {"at": "0.6", "event": "send arms; running text 'paste this into Claude…'"}]},
     "props": {"greeting": "Your turn.", "topic": "GODOT · WALKER", "segment": "Your walker game",
               "command": "Please use Walker to add one new sound event to my walker-TANK slice: a short click when the 0.8-second reload finishes. First add it to my event-to-sound map and predict how many clicks ten seconds of held fire should give. Then extend tests/test_sound_triggers.gd to count it, and only then edit the game code.",
               "runningText": "paste this into Claude…", "folderLabel": "@NikBearBrown", "modelLabel": "Claude",
               "effortLabel": "High", "animateTyping": True, "largeText": True}},
    {"beat_id": "B35", "act": "OUTRO", "role_note": "OUTRO-LOCK: outro_voice, spoken never scored, 1.0 s silent tail hold.",
     "narration_text": f"{TITLE}. At Nik Bear Brown.", "kind": "outro_voice", "tail_hold_s": 1.0,
     "pattern": "ClaudeTitleOutro",
     "shot": {"type": "GRAPHIC", "class": "SHOW", "source": "remotion",
              "show": [{"at": "0.0", "event": "exact title, @NikBearBrown, one slug-seeded crisp-safe mascot, no subline"},
                       {"at": "0.0", "event": "spoken only: title re-read, then 'At Nik Bear Brown'; 1.0 s silent tail"}]},
     "props": {"title": TITLE, "slug": SLUG}},
]
